ident: "search-service"

log:
  filter: 0
  caller: true
  output: "output"

mysql:
  dsn: "root:password@tcp(139.180.147.194:7000)/tgbot?charset=utf8mb4&parseTime=True&loc=Local"

elasticsearch:
  address:
    - http://139.180.147.194:7001
  username: "elastic"
  password: "password"

nats:
  address:
    - http://139.180.147.194:4222
    - http://139.180.147.194:4223
    - http://139.180.147.194:4224
  username: ""
  password: ""
  token: "mysecrettoken"

redis:
  address: "139.180.147.194:8765"
  password: "password"
  db: 1

web:
  prefix: "/v1"
  address: "0.0.0.0:9000"